### ISSUE TITLE
FlutterApplication.cs: Run(39) > Unhandled exception: System.DllNotFoundException

### ISSUE THREAD

**Issue by oysterlab** [flutter-tizen/flutter-tizen#66] opened 2021-03-31 13:40 UTC
when I command "flutter-tizen run"
saw this...

E/ConsoleMessage( 3746): FlutterApplication.cs: Run(39) > Unhandled exception: System.DllNotFoundException: Unable to load shared library 'flutter_engine.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libflutter_engine.so: cannot open shared object file: No such file or directory
E/ConsoleMessage( 3746):    at Tizen.Flutter.Embedding.Interop.FlutterEngineRunsAOTCompiledDartCode()
E/ConsoleMessage( 3746):    at Tizen.Flutter.Embedding.FlutterApplication.OnCreate()
E/ConsoleMessage( 3746):    at Runner.App.OnCreate()
E/ConsoleMessage( 3746):    at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
E/ConsoleMessage( 3746):    at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
E/ConsoleMessage( 3746):    at Tizen.Applications.CoreApplication.Run(String[] args)
E/ConsoleMessage( 3746):    at Tizen.Applications.CoreUIApplication.Run(String[] args)
E/ConsoleMessage( 3746):    at Tizen.Flutter.Embedding.FlutterApplication.Run(String[] args)
E/ConsoleMessage( 3746):    at Runner.App.Main(String[] args)

I run on mac

**Comment by swift-kim** [comment] 2021-03-31 13:52
Duplicate of #50.

**Closed by swift-kim** 2021-03-31 13:52 UTC
