### ISSUE TITLE
Destroy the plugin properly when exiting the app

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/flutter-tizen#90] opened 2021-04-22 04:44 UTC
According to my analysis, when using multiple plug-ins as shown below, only the last registered plugin is destroyed normally when exiting app. This is causing a crash at the end of the app. 

I guess that there are something wrong with implementations that deals with plugins in Tizen Embedder

```cs
//
// Generated file. Do not edit.
//
using System;
using System.Runtime.InteropServices;
using Tizen.Flutter.Embedding;

namespace Runner
{
    internal class GeneratedPluginRegistrant
    {
        [DllImport("camera_plugin.so")]
        public static extern void CameraPluginRegisterWithRegistrar(IntPtr registrar);
        [DllImport("integration_test_plugin.so")]
        public static extern void IntegrationTestPluginRegisterWithRegistrar(IntPtr registrar);
        [DllImport("video_player_tizen_plugin.so")]
        public static extern void VideoPlayerTizenPluginRegisterWithRegistrar(IntPtr registrar);

        public static void RegisterPlugins(FlutterApplication app)
        {
            CameraPluginRegisterWithRegistrar(app.GetPluginRegistrar("CameraPlugin"));
            IntegrationTestPluginRegisterWithRegistrar(app.GetPluginRegistrar("IntegrationTestPlugin"));
            VideoPlayerTizenPluginRegisterWithRegistrar(app.GetPluginRegistrar("VideoPlayerTizenPlugin"));
        }
    }
}

```

**Comment by bbrto21** [comment] 2021-04-22 04:46
Should I move this issue to the engine repo?

**Comment by swift-kim** [comment] 2021-04-22 05:26
> Should I move this issue to the engine repo?

Not necessarily but you can as this is an embedder issue.

Probably the behavior is caused by the following code:

https://github.com/flutter-tizen/engine/blob/31279eae37874150064da5983425c7769f0b0f40/shell/platform/common/cpp/client_wrapper/include/flutter/plugin_registrar.h#L106-L107

https://github.com/flutter-tizen/engine/blob/31279eae37874150064da5983425c7769f0b0f40/shell/platform/tizen/flutter_tizen.cc#L68-L72

I just followed other platform implementations (especially windows) when I was implementing the destruction handler for Tizen, although I also thought it's incorrect to overwrite existing handler when registering a new plugin. Now it's time to deal with this issue!

- Does Windows have the same problem? If not, why?
- Having a list of callbacks in the embedder and calling them one by one when stopping the engine will resolve the issue?

**Comment by bbrto21** [comment] 2021-04-22 06:51
> Does Windows have the same problem? If not, why?

I've never checked it on Windows, but I guess that they might have mistaken that there is no problem.
Because a typical plug-in behavior is operated passively by a method handler. On the other hand, the camera or video plugin is constantly calling engine API in the child thread of plugin side to pass media packets. 

I hope someone who is familiar with the Windows environment can experiment.

>Having a list of callbacks in the embedder and calling them one by one when stopping the engine will resolve the issue?

I'll try it later.

**Comment by swift-kim** [comment] 2021-04-23 08:36
This seems to be a tool issue and I'll prepare a fix soon. Until then, you can use the native app host (`--tizen-language cpp`) which doesn't have this issue. The issue is only reproducible with the .NET app host due to its unique plugin architecture.

**Comment by swift-kim** [comment] 2021-04-23 09:24
https://github.com/swift-kim/flutter-tizen/commit/b13462d7093c1b36330bf18dba678effd8fa2be2

This is a really quick fix for this issue (compiling all plugins into a single .so) but I actually have to re-design the entire architecture.

**Closed** 2021-05-04 00:34 UTC
Labels: bug
