### ISSUE TITLE
The Tizen Net Sdk Not Found Error. Every Time Building TPK

### ISSUE THREAD

**Issue by ncr9108** [flutter-tizen/flutter-tizen#152] opened 2021-06-29 14:04 UTC
![Capture](https://user-images.githubusercontent.com/26616810/123811577-fd75ec00-d910-11eb-88f6-f47f87c14c6d.PNG)

Every Packages And All Requirement Fullfiles.
Although Showing This Error.

**Comment by ncr9108** [comment] 2021-06-29 14:08
![Capture](https://user-images.githubusercontent.com/26616810/123812304-9b69b680-d911-11eb-871d-9d8250839d64.PNG)

Response Of :- flutter-tizen doctor -v

**Comment by swift-kim** [comment] 2021-06-29 15:48
Hmm, it's weird.

It looks like an issue with the NuGet SDK resolver in MSBuild and I was able to reproduce a similar error by commenting out all packageSources in the file `~/.nuget/NuGet/NuGet.Config` on Linux. (On Windows, the config file can be found at `%AppData%\NuGet\NuGet.config`.)

```
Building a Tizen application in release mode...                    590ms
Failed to build .NET application:
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/home/swift/Git/dummy/dummy_app/tizen/Runner.csproj : error : Unable to resolve 'Tizen.NET.Sdk (= 1.1.5)' for '.NETStandard,Version=v0.0'.
/home/swift/Git/dummy/dummy_app/tizen/Runner.csproj : error : Unable to resolve 'Tizen.NET.Sdk (= 1.1.5)' for '.NETStandard,Version=v0.0'.
/home/swift/Git/dummy/dummy_app/tizen/Runner.csproj : error MSB4236: The SDK 'Tizen.NET.Sdk/1.1.5' specified could not be found.

Build FAILED.

/home/swift/Git/dummy/dummy_app/tizen/Runner.csproj : error : Unable to resolve 'Tizen.NET.Sdk (= 1.1.5)' for '.NETStandard,Version=v0.0'.
/home/swift/Git/dummy/dummy_app/tizen/Runner.csproj : error : Unable to resolve 'Tizen.NET.Sdk (= 1.1.5)' for '.NETStandard,Version=v0.0'.
/home/swift/Git/dummy/dummy_app/tizen/Runner.csproj : error MSB4236: The SDK 'Tizen.NET.Sdk/1.1.5' specified could not be found.
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:00.16
```

A quick workaround for this issue would be creating a file named `NuGet.Config` next to `Runner.csproj` in the `tizen` directory with the following content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="tizen.myget.org" value="https://tizen.myget.org/F/dotnet/api/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

but it doesn't really fix the root cause of the problem. Which version of the .NET SDK do you have? Did you change any of its configuration?

@WonyoungChoi Do you have any idea regarding this error?

**Comment by WonyoungChoi** [comment] 2021-06-30 00:07
@swift-kim Is any `NuGet.config` file in the parent directories? such like `/home/swift/` or '/home/swift/Git/` or .....

**Comment by WonyoungChoi** [comment] 2021-06-30 00:09
please check the nuget source list with:
```
$ dotnet nuget list source
```

**Comment by swift-kim** [comment] 2021-06-30 00:35
@WonyoungChoi No, I made sure no `NuGet.config` exists in `tizen` and its parent directories, and also deleted existing nuget caches in `~/.nuget/packages`.

**Comment by ncr9108** [comment] 2021-06-30 04:12
![Capture](https://user-images.githubusercontent.com/26616810/123900780-56806700-d987-11eb-8df7-1ac2ea316df3.PNG)

My Problem Resolved By Adding

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="tizen.myget.org" value="https://tizen.myget.org/F/dotnet/api/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>

This in Nuget.config file.

**Comment by ncr9108** [comment] 2021-06-30 04:15
@swift-kim  Thank you. 👍🏻

**Comment by swift-kim** [comment] 2021-06-30 04:33
Mmm, that's not what I asked you to do (I actually wanted you to help us find the root cause of the problem but what you have done is irreversible and now there's nothing we can do). Anyway, I'm glad your problem has been solved. I'll close the issue.

**Closed by swift-kim** 2021-06-30 04:33 UTC

**Comment by ncr9108** [comment] 2021-06-30 04:54
OKay...

![Capture](https://user-images.githubusercontent.com/26616810/123903998-56836580-d98d-11eb-9690-2eb84a88b0b6.PNG)

Previously that file have this data. Check it out. if it can help you to find root cause of problem.

**Comment by swift-kim** [comment] 2021-06-30 05:18
@ncr9108 Oh, thank you for the information. I'm not sure why your `NuGet.config` had been corrupted, but I will prepare some patch if the same problem is reported by other users.
