### ISSUE TITLE
TV SDK could not be found. Trying with Wearable SDK... 

### ISSUE THREAD

**Issue by curtlowellv** [flutter-tizen/flutter-tizen#336] opened 2022-02-24 01:58 UTC
Hello Flutter tizen noobie here!

I just want some help in fixing this one. I cannot find enough documentations about this issue. This happened when I try running the app with this **webview_flutter_tizen: ^0.3.10** added in the pubspec.yaml (as per plugin documentation says.). I cannot successfully run the app in my TV emulator(don't have physical device). Attached screenshots are my pubspec.yaml configuration and the error. Thanks in advance.

![image](https://user-images.githubusercontent.com/100327297/155442656-50e65603-26c0-46c6-9e76-94a73461ea10.png)
![image](https://user-images.githubusercontent.com/100327297/155442680-6f62ce7e-5465-49f1-a0c2-312f315d4a66.png)
![image](https://user-images.githubusercontent.com/100327297/155442724-3d22efd1-7cec-42d3-b729-7ec43e9f4cc6.png)
![image](https://user-images.githubusercontent.com/100327297/155442775-feb676b5-a6c1-46df-a138-b0cefa4c45a4.png)

**Comment by swift-kim** [comment] 2022-02-24 04:51
> TV SDK could not be found. Trying with Wearable SDK.

This message itself is normal because Samsung TVs do not officially come with native app build support (only web and .NET are supported) and the tool automatically falls back to the Wearable SDK. The message will appear when you build any flutter-tizen plugin but not only webview_flutter_tizen.

Probably your build has failed because webview_flutter_tizen is not supported on emulator devices (see the [Device limitations](https://github.com/flutter-tizen/plugins#device-limitations) section in the repo's README). Currently there's no web engine binary available for emulator devices (x86) as you can see in https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter/tizen/lib. We're sorry for not clearly mentioning this in the plugin README.

@bwikbs @bbrto21 Do you have any plan to add support for the x86 architecture?

**Comment by curtlowellv** [comment] 2022-02-24 05:06
> > TV SDK could not be found. Trying with Wearable SDK.
> 
> This message itself is normal because Samsung TVs do not officially come with native app build support (only web and .NET are supported) and the tool automatically falls back to the Wearable SDK. The message will appear when you build any flutter-tizen plugin but not only webview_flutter_tizen.
> 
> Probably your build has failed because webview_flutter_tizen is not supported on emulator devices (see the [Device limitations](https://github.com/flutter-tizen/plugins#device-limitations) section in the repo's README). Currently there's no web engine binary available for emulator devices (x86) as you can see in https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter/tizen/lib. We're sorry for not clearly mentioning this in the plugin README.
> 
> @bwikbs @bbrto21 Do you have any plan to add support for the x86 architecture?

Alright will be checking the link you have provided and thank you for clarifying things.

**Comment by bwikbs** [comment] 2022-03-08 05:26
@swift-kim @curtlowellv 
I'm sorry for late response. WebView for the emulator is currently being prepared. 
But it's delayed for other priority issue. and If you want, you can use the following temporary patches.
https://github.com/bwikbs/plugins/commit/2f4e2461dbe8219f3b8b6def7c507c6fbda12e49
I confirmed the operation in the 6.5 TV emulator today.
(Because of the current internal behavior issue, it is recommended that you test on sites like naver, not the apahe license.)

**Comment by swift-kim** [comment] 2022-03-30 03:10
The emulator (x86 architecture) support has been added to [webview_flutter_tizen 0.4.0](https://pub.dev/packages/webview_flutter_tizen) but it's still in an early stage and has [some bugs](https://github.com/flutter-tizen/plugins/issues/339). More work will be done on the package in the future. I'll close this issue anyway.

**Closed by swift-kim** 2022-03-30 03:10 UTC
