### ISSUE TITLE
Rotating bezel crashes PageView

### ISSUE THREAD

**Issue by almararn** [flutter-tizen/flutter-tizen#428] opened 2022-08-21 20:57 UTC
My app has multiple screens created with PageView builder.  If the (virtual) bezel on the Galaxy Watch Active 2 is accidentally touched during transitions between those screens, the app will become completely unresponsive.  This happens with or without the wearable_rotary package being installed or used.  I am unable to replicate this error on the tizen emulator, but this always happens on the physical device. (Tizen 5.5.0.2)

I can however install the wearable_rotary package and use the bezel to switch between screens without any major problems.  But the app is so easily crashable if swiping between screens manually and accidentally touching the bezel, that I cant publish it in that state.

Any thoughts on this?

**Comment by swift-kim** [comment] 2022-08-23 01:29
Hi. I couldn't reproduce this issue with the wearable_rotary example app on my Galaxy Watch Active running Tizen 5.5.0. Do you have any sample code or specific steps to reproduce the issue?

Maybe you can get a stack trace of the crashed app by attaching a debugger (GDB) to it. The detailed instructions can be found at https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-app's-native-code. You will have to change the app language to C++ and use the `bt` command from the GDB console to print a stack trace.

**Comment by almararn** [comment] 2022-08-24 16:59
Hi, yes I also tried the wearable_rotary example app, and the touchscreen becomes unresponsive if you manually slide between screens and then turn the rotating bezel while the screens are being animated in place.  The rotating bezel keeps on working though to change screens, so the only difference on this particular app is that you cant manually slide it anymore, because the touchscreen has stopped working.

Using the wearable_rotary package to change screens actually greatly reduces the chance of the app crashing and the touchscreen getting unresponsive.  But on a simple demo app like this: https://github.com/almararn/pageview_example
not using the rotary package at all, it's easier to reproduce the issue.

I'm not sure I have the skills to get a stack trace, but I could give it a go.  But I did make this 30 sec video, using the demo app I created, showing the problem and what happens when sliding between screens and accidentally touching the rotating bezel:  https://youtu.be/pV21wOv3LNM

**Comment by swift-kim** [comment] 2022-08-25 14:28
Sorry, I still can't reproduce the issue. I tested both your app and the wearable_rotary example app on my watches (GW3 and GWA) but they worked fine.

As far as I see in your video, it feels like some kind of device (hardware) issue. Maybe the device thinks its screen is still being touched (not receiving touch "up" event) even after you lift your finger off the screen, and thus the next time you tap and move your finger it thinks you're swiping with two fingers. I can provide you a similar non-Flutter demo app written in C++/C# if you want to double check (or you can write one by referring to the CircularUI [IRotaryEventReceiver](https://samsung.github.io/Tizen.CircularUI/guide/IRotaryEventReceiver.html) guide).

Also the stack trace will not help in this case so you don't have to give a try. :)

**Comment by almararn** [comment] 2022-08-25 21:33
Hi, yes it only happens in flutter apps, and only during transition between screens.  I did try both Calendar and Gallery on the watch and the issue did not appear there, no matter how hard I tried.  And after the flutter app becomes unresponsive I can exit it with the home key and everything works normally on the watch, even other flutter apps.  And when I enter the app again it is still in the non responsive state.  It's only until after I press the back key to kill the app and restart it, it will become normal again.

Wonder if it's possible to have flutter app completely ignore the rotary bezel?

This evening I tried a full factory restore on the watch.  But the issue still remains.
Maybe it's something to do with the model number, and it having less memory? SM-R820

**Comment by swift-kim** [comment] 2022-08-26 06:43
Thank you. It would be nice if you could help me verify a few more things:

[Here](https://github.com/swift-kim/warehouse/raw/master/data/bezel_test.zip) is a zip file which contains three `libflutter_tizen_wearable.so` files (which we call an embedder). You can copy the file into

```
flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-arm-release/libflutter_tizen_wearable.so
```

on your local hard drive and that file will be used on next app build. Please make sure to build the app in release mode (`flutter-tizen run --release`).

- **01_normal:** This is our latest embedder build with no code change but will print some additional logs in the console when you touch the device screen.
- **02_ecore_wl2:** This uses a different rendering backend and may generate a different result.
- **03_simulate:** This simulates a touch "up" event if it's not received until the next "down" event (to make sure "up" events are always sent before "down" events).

Please let us know if you found anything strange in the logs (for example, repeated "Pointer DOWN" events without "Pointer UP" between them) or anything that may help us debug the issue.

Note: You can restore the file back to the original one by running `flutter-tizen precache --tizen --force`.

**Comment by swift-kim** [comment] 2022-08-26 07:04
> Wonder if it's possible to have flutter app completely ignore the rotary bezel?

Unfortunately I couldn't find any way to do this ([EFL reference](https://docs.tizen.org/application/native/guides/ui/efl/rotary-events/)).

**Comment by almararn** [comment] 2022-08-26 19:50
Good job! :) This fixes the issue.  01 and 03 both work perfectly with no problems, while 02 still crashes like before.
I didn't receive any error messages, just got the touchscreen feedback in the console.

![Screenshot 2022-08-26 at 19 30 39](https://user-images.githubusercontent.com/61119003/186980189-7cd6442f-2936-4f3b-99c9-39e1bcc30707.png)

**Comment by swift-kim** [comment] 2022-08-27 15:46
Hum, I didn't actually expect that result but anyway that's a good news. It seems the issue has already been fixed by [one](https://github.com/flutter-tizen/engine/commit/5d137157585d0c98c246b4549a0c608088fd2731) of our latest patches and the fix will be available in our master channel when https://github.com/flutter-tizen/flutter-tizen/pull/432 is merged.

Please let me know if https://github.com/flutter-tizen/flutter-tizen/pull/432 doesn't fix your problem.

**Comment by almararn** [comment] 2022-08-28 10:44
Yes, thanks It has fixed the issue.

I do though have a problem after updating flutter-tizen to 3.0.5, I can only run apps in debug mode, else when using release mode I get the error "Can't load Kernel binary: Invalid SDK hash" I cant seem to find a solution for that, is that something you know?

I can only use a version I downloaded i June, that has flutter 3.0.0 to run in release mode.

I'll attach flutter-tizen doctor and error:
![Screenshot 2022-08-21 at 19 50 59](https://user-images.githubusercontent.com/61119003/187068795-412d1623-16e3-4638-b99d-326de9ebd8e1.png)
![Screenshot 2022-08-28 at 09 48 17](https://user-images.githubusercontent.com/61119003/187068807-7bca31e5-e748-4c9c-bfee-c38a92d9db92.png)

**Comment by swift-kim** [comment] 2022-08-28 12:09
Oops. I managed to reproduce the issue on my Macbook. It seems something went wrong with our CI server and it's not automatically rebuilding AOT snapshotter for macOS and is using a cached snapshotter for previous version (3.0.0). Thank you for reporting and we'll check and prepare a fix as soon as possible.

**Closed** 2022-08-29 04:31 UTC
Labels: bug, embedder
